name: ci

on:
 push:
 pull_request:

jobs:
 canary:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Build Container
       run: docker build -t bluesky/databroker:latest .

     # - name: Install Container Canary
     #   run: |
     #     curl -L https://github.com/NVIDIA/container-canary/releases/download/v0.2.1/canary_linux_amd64 > /usr/local/bin/canary
     #     chmod +x /usr/local/bin/canary
     # 
     # - name: Validate container
     #   run: canary validate --file canary-validator.yml bluesky/databroker:latest
